services:

  api:
    build:
      context: ./${API_DIRECTORY}
      dockerfile: ../docker/api/Dockerfile
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ${API_DIRECTORY}:/var/www/project/api
      - ./docker/api/xdebug.ini:/usr/local/etc/php/conf.d/docker-xdebug.ini
    environment:
      XDEBUG_SESSION: 1
      XDEBUG_MODE: debug, develop
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - ${PROJECT_NAME}

  frontend-personnel:
    build:
      context: frontend-personnel
      dockerfile: ../docker/frontend-personnel/Dockerfile
    command: npm start
    stdin_open: true
    tty: true
    container_name: ${PROJECT_NAME}-frontend-personnel
    volumes:
      - ${FRONTEND_PERSONNEL_DIRECTORY}:/var/www/project/frontend-personnel
      - /var/www/project/frontend-personnel/node_modules
    networks:
      - ${PROJECT_NAME}

  frontend-guest:
    build:
      context: frontend-guest
      dockerfile: ../docker/frontend-guest/Dockerfile
    command: npm run build
    stdin_open: true
    tty: true
    container_name: ${PROJECT_NAME}-frontend-guest
    volumes:
      - ${FRONTEND_GUEST_DIRECTORY}:/var/www/project/frontend-guest
      - /var/www/project/frontend-guest/node_modules
    networks:
      - ${PROJECT_NAME}

  mysql:
    image: mysql:8.0.20
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ${PROJECT_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    networks:
      - ${PROJECT_NAME}


  nginx:
    build: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ${API_DIRECTORY}:/var/www/project/api
      - ${FRONTEND_PERSONNEL_DIRECTORY}:/var/www/project/frontend-personnel
      - ${FRONTEND_GUEST_DIRECTORY}:/var/www/project/frontend-guest
      - ./docker/certs/local:/etc/nginx/certs
    networks:
      - ${PROJECT_NAME}
    environment:
      NODE_ENV: dev
      NGINX_HOST: ${NGINX_HOST_LOCAL}
      NGINX_PORT: ${NGINX_PORT_LOCAL}
      NGINX_CERT_CRT: ${NGINX_CERT_CRT_LOCAL}
      NGINX_CERT_KEY: ${NGINX_CERT_KEY_LOCAL}
    depends_on:
      - frontend-personnel
      - frontend-guest

networks:
  project:


volumes:
  mysql:
